# Autogenerated wrapper script for X42Darc_jll for x86_64-linux-musl
export darc_bin, darc_lv2

using lv2_jll
JLLWrappers.@generate_wrapper_header("X42Darc")
JLLWrappers.@declare_library_product(darc_bin, "darc.so")
JLLWrappers.@declare_file_product(darc_lv2)
function __init__()
    JLLWrappers.@generate_init_header(lv2_jll)
    JLLWrappers.@init_library_product(
        darc_bin,
        "share/lv2/darc.lv2/darc.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_file_product(
        darc_lv2,
        "share/lv2/darc.lv2/manifest.ttl",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
